<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Discharge 22 Feb</name>
   <tag></tag>
   <elementGuidId>e863ac50-472e-4262-8160-0967cdff0438</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>22</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;hospitalStayDischarge-calendar&quot;)/div[@class=&quot;displayContainer&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;datePickerMonth&quot;]/table[1]/tbody[1]/tr[4]/td[@class=&quot;hovered&quot;]/span[1]</value>
   </webElementProperties>
</WebElementEntity>
