<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h2_Request treatment pre-appro</name>
   <tag></tag>
   <elementGuidId>f223d380-8bcd-4781-9899-eab09e8a1bd8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#requesting-treatment-slide1</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'requesting-treatment-slide1']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;requesting-treatment-slide1&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Request treatment pre-approval</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;requesting-treatment-slide1&quot;)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>selector</name>
      <type>Main</type>
      <value>#requesting-treatment-slide1</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>requesting-treatment-slide1</value>
   </webElementProperties>
</WebElementEntity>
