<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_navigation-link</name>
   <tag></tag>
   <elementGuidId>cf5767f2-769e-4ae4-a734-a7edda90ae20</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.carousel-button:nth-child(2)</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@title = 'Treatment authorisation']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://bupa.portal.sitecore.qa.hwuat.co.uk:443/treatment-authorisation</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>navigation-link</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Treatment authorisation</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_self</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;module-3&quot;)/div[@class=&quot;scrollableContent&quot;]/nav[@class=&quot;primary-navigation&quot;]/ul[1]/li[@class=&quot;navigation-item has-icon&quot;]/a[@class=&quot;navigation-link&quot;]</value>
   </webElementProperties>
</WebElementEntity>
