<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Carousel_img_TreAuth</name>
   <tag></tag>
   <elementGuidId>d0efef5c-6c93-4dc0-8c8a-f537f08bdb2f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.carousel-item:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(1) > img:nth-child(1)</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;primaryPanel&quot;)/div[@class=&quot;logo-container&quot;]/div[@class=&quot;logo-container-inner&quot;]/a[@class=&quot;logo&quot;]/img[1][count(. | //img[@src = 'https://bupa.portal.sitecore.qa.hwuat.co.uk:443/-/media/bupa/images/bupa-logo.png?h=78&amp;w=176&amp;la=en&amp;hash=C9E6943CBC3D8B512039313EFBA0CB5FDF3E0EF4' and @alt = 'Bupa']) = count(//img[@src = 'https://bupa.portal.sitecore.qa.hwuat.co.uk:443/-/media/bupa/images/bupa-logo.png?h=78&amp;w=176&amp;la=en&amp;hash=C9E6943CBC3D8B512039313EFBA0CB5FDF3E0EF4' and @alt = 'Bupa'])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://bupa.portal.sitecore.qa.hwuat.co.uk:443/-/media/bupa/images/bupa-logo.png?h=78&amp;w=176&amp;la=en&amp;hash=C9E6943CBC3D8B512039313EFBA0CB5FDF3E0EF4</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Bupa</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;primaryPanel&quot;)/div[@class=&quot;logo-container&quot;]/div[@class=&quot;logo-container-inner&quot;]/a[@class=&quot;logo&quot;]/img[1]</value>
   </webElementProperties>
</WebElementEntity>
