<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_hospitalAdmittanceDay</name>
   <tag></tag>
   <elementGuidId>a486efd3-3ed5-40e1-9321-3e1c6f78e6fb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//input[count(. | //*[@type = 'tel']) = count(//*[@type = 'tel'])][count(. | //*[@id = 'hospitalAdmittanceDay']) = count(//*[@id = 'hospitalAdmittanceDay'])][count(. | //*[@placeholder = 'DD']) = count(//*[@placeholder = 'DD'])][count(. | //*[@pattern = '[0-9]*']) = count(//*[@pattern = '[0-9]*'])][count(. | //*[@aria-labelledby = 'hospitalAdmittanceLegendLabel hospitalAdmittanceDayLabel']) = count(//*[@aria-labelledby = 'hospitalAdmittanceLegendLabel hospitalAdmittanceDayLabel'])][count(. | //*[@aria-describedby = 'hospitalAdmittanceDayHelper']) = count(//*[@aria-describedby = 'hospitalAdmittanceDayHelper'])][count(. | //*[@name = 'hospitalAdmittanceDay']) = count(//*[@name = 'hospitalAdmittanceDay'])][count(. | id(&quot;hospitalAdmittanceDay&quot;)) = count(id(&quot;hospitalAdmittanceDay&quot;))]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>tel</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>hospitalAdmittanceDay</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>DD</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>[0-9]*</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>hospitalAdmittanceLegendLabel hospitalAdmittanceDayLabel</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>hospitalAdmittanceDayHelper</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>hospitalAdmittanceDay</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;hospitalAdmittanceDay&quot;)</value>
   </webElementProperties>
</WebElementEntity>
