<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_signInUsername</name>
   <tag></tag>
   <elementGuidId>7556dfa4-d99b-4821-9daa-606003620eec</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#signInUsername</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;signInUsername&quot;)[count(. | //input[@id = 'signInUsername' and @class = 'textInput' and @type = 'text' and @placeholder = 'undefined' and @aria-required = 'true' and @aria-label = 'This information is required., Please enter your username']) = count(//input[@id = 'signInUsername' and @class = 'textInput' and @type = 'text' and @placeholder = 'undefined' and @aria-required = 'true' and @aria-label = 'This information is required., Please enter your username'])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>signInUsername</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>textInput</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>undefined</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>This information is required., Please enter your username</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;signInUsername&quot;)</value>
   </webElementProperties>
</WebElementEntity>
